IMAGE:
  WIDTH: 640
  HEIGHT: 480
  ROI_START_HEIGHT: 340
  ROI_HEIGHT: 40

XYCAR:
  START_SPEED: 20.0
  MAX_SPEED: 30.0
  MIN_SPEED: 10.0
  SPEED_CONTROL_THRESHOLD: 15.0
  ACCELERATION_STEP: 0.1
  DECELERATION_STEP: 2.0
  ACCELERATION_STEP_S: 0.1
  DECELERATION_STEP_S: 0.4

PID:
  P_GAIN: 0.38
  I_GAIN: 0.0006
  D_GAIN: 1.5

MOVING_AVERAGE_FILTER:
  SAMPLE_SIZE: 4
  SAMPLE_SIZE_FOR_ERROR: 10

TOPIC:
  PUB_NAME: /xycar_motor
  SUB_NAME: /usb_cam/image_raw/
  QUEUE_SIZE: 1

CANNY:
  LOW_THRESHOLD: 230
  HIGH_THRESHOLD: 270

HOUGH:
  ABS_SLOPE_RANGE: 10.0
  THRESHOLD: 40
  MIN_LINE_LENGTH: 35
  MAX_LINE_GAP: 10

DEBUG: true
